version: '3'

services:
  users-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${USERS_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${USERS_DATASOURCE_PASSWORD:-password}
    volumes:
      - users-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  users-data:
