server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/spring"
              scopes:
                - "openid"
                - "user.read"
                - "user.write"
            require-authorization-consent: true

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}

  jpa:
    generate-ddl: true

  flyway:
    enabled: false
    baseline-on-migrate: true

logging:
  level:
    '[org.springframework.security]': TRACE
