spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "https://oauthdebugger.com/debug"
              scopes:
                - "openid"
            require-authorization-consent: true

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}

  jpa:
    generate-ddl: true

  flyway:
    enabled: false
    baseline-on-migrate: true
logging:
  level:
    '[org.springframework.boot]': TRACE
